version: '3'
services:
  web:
    build: .
    privileged: true
    ports:
      - "4200:4200"
    volumes:
      - ..:/opt/project
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
    working_dir: /opt/project
    command: sh -c 'npm install && npm start'
  api:
    image: node:9.7-alpine
    ports:
      - "3000:3000"
    volumes:
      - ../api_server:/opt/project
    working_dir: /opt/project
    command: sh -c 'npm install && npm start'
